version: "3"
services:
  burrow-node-0:
    image: hyperledger/burrow:0.23.1
    container_name: burrow_0
    network_mode: host
    volumes:
    - ./chain:/chain
    working_dir: /chain
    environment:
      NODEID: 0
    entrypoint: ./startup.sh

  burrow-node-1:
    image: hyperledger/burrow:0.23.1
    container_name: burrow_1
    network_mode: host
    volumes:
    - ./chain:/chain
    working_dir: /chain
    environment:
      NODEID: 1
    entrypoint: ./startup.sh
