sdk: "configs/accelerator-sdk.yaml"
host: "0.0.0.0"
port: 8090
userName: "Admin"
organization: "org1.example.com"
batch:
##### Simple #####
  - type: "execute"
    channelId: "mychannel"
    chaincode: "simple"
    fcn: "open"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "execute"
    channelId: "mychannel"
    chaincode: "simple"
    fcn: "delete"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "query"
    channelId: "mychannel"
    chaincode: "simple"
    fcn: "query"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "execute"
    channelId: "mychannel"
    chaincode: "simple"
    fcn: "transfer"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
##### Smallbank #####
  - type: "execute"
    channelId: "mychannel"
    chaincode: "smallbank"
    fcn: "create_account"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "execute"
    channelId: "mychannel"
    chaincode: "smallbank"
    fcn: "transact_savings"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "execute"
    channelId: "mychannel"
    chaincode: "smallbank"
    fcn: "deposit_checking"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "execute"
    channelId: "mychannel"
    chaincode: "smallbank"
    fcn: "send_payment"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "execute"
    channelId: "mychannel"
    chaincode: "smallbank"
    fcn: "write_check"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "execute"
    channelId: "mychannel"
    chaincode: "smallbank"
    fcn: "amalgamate"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"
  - type: "query"
    channelId: "mychannel"
    chaincode: "smallbank"
    fcn: "query"
    queueSize: 1000
    maxWaitTimeSeconds: 5
    maxItem: 10
    recoveryPolicy: "retry"